"""Build a shared arith-common.css for the 4 arithmetic apps and reduce each
per-app CSS to only its unique rules.

Rule placement:
  * selector in >= 2 of the 4 apps  -> arith-common.css (majority body wins;
                                       ties broken by app order 38,45,47,48)
  * selector in exactly 1 app       -> stays in that app's css

Each per-app css is rewritten to contain only its unique selectors.
Originals are backed up to css/_backup_pre_common/.
"""
import os, re, shutil
from collections import defaultdict, Counter, OrderedDict

CSS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "css")
APPS = ["FractionApp38", "FractionApp45", "FractionApp47", "FractionApp48"]
DRY = False

def strip_comments(css):
    return re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)

def parse_rules(css):
    """Return list of (selector, raw_inner_body) preserving order; bodies keep
    their original text (trimmed) so we re-emit readable CSS."""
    css = strip_comments(css)
    out, depth, token = [], 0, ""
    for c in css:
        token += c
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                m = re.match(r"\s*(.*?)\{(.*)\}\s*$", token, re.DOTALL)
                if m:
                    sel = re.sub(r"\s+", " ", m.group(1)).strip()
                    body = m.group(2).strip()
                    out.append((sel, body))
                token = ""
    return out

def norm_body(body):
    """Whitespace-normalized form for equality comparison."""
    b = re.sub(r"\s+", " ", body).strip()
    b = re.sub(r"\s*;\s*", "; ", b).strip().rstrip(";").strip()
    return b

def fmt_rule(sel, body):
    """Pretty-print a rule. @media keeps its raw (already-braced) body."""
    if sel.startswith("@media") or sel.startswith("@keyframes") or sel.startswith("@supports"):
        inner = body.strip()
        return f"{sel} {{\n{indent(inner)}\n}}\n"
    decls = [d.strip() for d in body.split(";") if d.strip()]
    lines = "\n".join(f"    {d};" for d in decls)
    return f"{sel} {{\n{lines}\n}}\n"

def indent(text, pad="    "):
    return "\n".join(pad + l if l.strip() else l for l in text.splitlines())

# --- parse all apps ---
# Restore from backup first so this script is idempotent / re-runnable.
backup = os.path.join(CSS, "_backup_pre_common")
if os.path.isdir(backup):
    for a in APPS:
        src = os.path.join(backup, a + ".css")
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(CSS, a + ".css"))

app_rules = {}
for a in APPS:
    with open(os.path.join(CSS, a + ".css"), encoding="utf-8") as f:
        app_rules[a] = parse_rules(f.read())

# selector -> ordered {app: body}
sel_app_body = defaultdict(OrderedDict)
sel_order = []  # first-seen order, scanning apps in APPS order
for a in APPS:
    for sel, body in app_rules[a]:
        if sel not in sel_app_body:
            sel_order.append(sel)
        sel_app_body[sel][a] = body

common, unique = [], defaultdict(list)
report = {"identical": 0, "resolved": 0, "unique": 0}
resolved_notes = []
FORCE_PER_APP = ("@media",)  # these differ by app-specific DOM; keep per app

for sel in sel_order:
    m = sel_app_body[sel]
    if sel.startswith(FORCE_PER_APP):
        # keep each app's own version of this rule, do not merge
        for a, b in m.items():
            unique[a].append((sel, b))
            report["unique"] += 1
        continue
    if len(m) >= 2:
        bodies = [norm_body(b) for b in m.values()]
        cnt = Counter(bodies)
        winner_norm, wcount = cnt.most_common(1)[0]
        # pick the first app (in APPS order) whose body matches the winner,
        # and use that app's ORIGINAL (unnormalized) body text.
        chosen = next(b for a, b in m.items() if norm_body(b) == winner_norm)
        common.append((sel, chosen))
        if len(set(bodies)) == 1:
            report["identical"] += 1
        else:
            report["resolved"] += 1
            losers = sorted({a[-2:] for a, b in m.items() if norm_body(b) != winner_norm})
            resolved_notes.append(f"{sel}  (normalized; differed in app {','.join(losers)})")
    else:
        a = next(iter(m))
        unique[a].append((sel, m[a]))
        report["unique"] += 1

# --- backup ---
if not DRY:
    os.makedirs(backup, exist_ok=True)
    for a in APPS:
        shutil.copy2(os.path.join(CSS, a + ".css"), os.path.join(backup, a + ".css"))

# --- write common ---
header = ("/* arith-common.css\n"
         "   Shared styles for the 4 arithmetic fraction apps\n"
         "   (Division 38, Multiplication 45, Addition 47, Subtraction 48).\n"
         "   Generated by build_common.py - edit shared rules here, not per app. */\n\n")
common_css = header + "\n".join(fmt_rule(s, b) for s, b in common)
if not DRY:
    with open(os.path.join(CSS, "arith-common.css"), "w", encoding="utf-8") as f:
        f.write(common_css)

# --- rewrite per-app files to unique-only ---
for a in APPS:
    if unique[a]:
        body = "\n".join(fmt_rule(s, b) for s, b in unique[a])
        content = (f"/* {a}.css - app-specific overrides only.\n"
                   f"   Shared rules live in arith-common.css (loaded first). */\n\n" + body)
    else:
        content = (f"/* {a}.css - no app-specific rules; everything shared.\n"
                   f"   See arith-common.css. */\n")
    if not DRY:
        with open(os.path.join(CSS, a + ".css"), "w", encoding="utf-8") as f:
            f.write(content)

print("Rules -> common:", len(common),
      f"(identical={report['identical']}, resolved={report['resolved']})")
print("Rules -> per-app unique:", report["unique"])
for a in APPS:
    print(f"  {a}: {len(unique[a])} unique -> {[s for s,_ in unique[a]]}")
print("\nResolved (value normalized to majority):")
for n in resolved_notes:
    print("  -", n)
print(f"\nBackup of original per-app css -> {backup}")
